name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release -r win-x64
          dotnet publish -c Release -r linux-x64

      - name: Test
        run: dotnet test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/Release/net7.0/win-x64/publish/connstr-test.exe
            bin/Release/net7.0/linux-x64/publish/connstr-test
